version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.4.3
jobs:
    build:
        working_directory: ~/docgeni
        docker:
            - image: cimg/node:22.13.0-browsers
        steps:
            - browser-tools/install-chrome
            - checkout
            - run: corepack enable
            - restore_cache:
                  key: docgeni-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
            - run: pnpm install --frozen-lockfile
            - save_cache:
                  key: pnpm install --frozen-lockfile
                  paths:
                      - 'node_modules'
            - run: pnpm lint
            - run: pnpm test-coverage
            - run: pnpm test-template --no-watch --no-progress --browsers=ChromeHeadlessCI
            - run: pnpm report-coverage
