export const SITE_ASSETS_RELATIVE_PATH = 'src/assets';
export const ASSETS_CONTENT_RELATIVE_PATH = `${SITE_ASSETS_RELATIVE_PATH}/content`;
export const ASSETS_EXAMPLES_SOURCE_RELATIVE_PATH = `${ASSETS_CONTENT_RELATIVE_PATH}/examples-source`;
export const ASSETS_EXAMPLES_HIGHLIGHTED_RELATIVE_PATH = `${ASSETS_CONTENT_RELATIVE_PATH}/examples-highlighted`;
export const ASSETS_OVERVIEWS_RELATIVE_PATH = `${ASSETS_CONTENT_RELATIVE_PATH}/overviews`;
export const ASSETS_API_DOCS_RELATIVE_PATH = `${ASSETS_CONTENT_RELATIVE_PATH}/api-docs`;
export const ASSETS_DOCS_RELATIVE_PATH = `${ASSETS_CONTENT_RELATIVE_PATH}/docs`;

export const DEFAULT_COMPONENT_DOC_DIR = 'doc';
export const DEFAULT_COMPONENT_API_DIR = 'api';
export const DEFAULT_COMPONENT_EXAMPLES_DIR = 'examples';
